# Generated by Django 2.2 on 2019-04-06 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todobackend', '0002_auto_20190404_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
